#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Regular, unpinned domain walls on the three FLRW spatial sections.

Companion calculation to

    "Spatial curvature, boundary pinning and the S^3 sphaleron: the Hessian
     spectrum of phi^4 interfaces in Friedmann-Lemaitre-Robertson-Walker spacetimes"

This script drops the inner Dirichlet datum of the main text and asks for
genuine static solutions that are regular at every center and interpolate
between the two vacua.  Three results:

  (i)  no-go       : on R^3 and H^3 no CENTERED, SPHERICALLY SYMMETRIC such
                     solution approaching a single vacuum at infinity exists,
                     for any coupling.  The obstruction is the virial identity
                         V(phi(0)) + int_0^inf 2 ctn_k (phi')^2 dchi = 0,
                     both terms of which are nonnegative when ctn_k > 0.
                     The boundary term at infinity vanishes because phi -> v
                     with V(v) = 0 and because phi' -> 0 there: linearizing
                     about the vacuum gives exponential decay of both phi - v
                     and phi'.
                     On S^3, cot changes sign at pi/2 and the obstruction is
                     absent.  The restriction to the centered radial class is
                     essential: the planar kink v tanh(m z / sqrt 2) is a
                     perfectly regular static wall on R^3, and layered
                     solutions on hyperbolic space are known in the
                     Allen-Cahn literature.  Neither is centered and radial.
  (ii) existence   : on S^3 an equatorial wall exists iff lambda v^2 a^2 > 3.
                     The threshold is the crossing of the second s-wave level
                     of the barrier-top solution phi = 0, whose reduced
                     spectrum obeys a^2 lam_n = n^2 - lambda v^2 a^2 - 1.
                     After u = phi/v and eps^2 = 1/(lambda v^2 a^2) this is the
                     Allen-Cahn equation on S^3, and the closed-section facts
                     recomputed here (existence threshold, equatorial nodal
                     set, Morse index one, isometry-generated kernel) are
                     those of Caju, Gaspar, Guaraco and Matthiesen,
                     Calc. Var. PDE 61 (2022) 71 [arXiv:2006.10607], whose
                     condition eps < 1/sqrt(N) is exactly lambda v^2 a^2 > 3
                     for N = 3.  The noncompact no-go of (i) is not in that
                     reference.
  Existence for every coupling above threshold follows from a variational
  argument in the paper: with Gamma = O(3) x Z_2 acting by phi -> phi o R for
  R in the isotropy subgroup fixing the poles, and by phi -> -phi o sigma for
  sigma the equatorial reflection, the fixed-point set of Gamma is exactly the
  radial, equatorially odd class.  The direct method plus Palais' principle of
  symmetric criticality then gives a nontrivial critical point.  The rotations
  matter: the odd subspace alone also contains non-radial fields.  The shooting
  computation below constructs that solution directly.

  (iii) index      : that wall is a sphaleron.  Differentiating the profile
                     equation gives, exactly,
                         H_(j=0) phi0' = -(2/(a^2 S^2)) phi0',
                         H_(j=1) phi0' = 0,
                     written at a = 1 below, as in section 6 of the paper,
                     so the s-wave quadratic form on phi0' is strictly
                     negative while the j = 1 sector carries an exact,
                     threefold-degenerate kernel generated by the isometries.
                     The index is exactly 1: phi0 is odd under the
                     equatorial reflection, so V''(phi0) is even, H_(j=0)
                     commutes with that reflection, and by Sturm
                     oscillation the first excited s-wave state is odd;
                     nonnegativity of the second variation on the odd
                     class then leaves only the even ground state
                     negative.  The runs below realize that index.

Conventions: a = v = 1 and lambda variable, so m^2 = lambda v^2 = lambda.
Because lambda changes along the tables below, eigenvalues are quoted in
units of a^{-2}, NOT in units of lambda v^2.  A quick check of that
convention: H_(j=2) - H_(j=1) = 4/sin^2(chi) >= 4 and lam_min(j=1) = 0,
so lam_min(j=2) >= 4 exactly, which the printed values satisfy.

Usage
-----
    python3 wall_numerics.py
    python3 wall_numerics.py --figure     # also writes figs/flrw/fig4_wall.pdf

Requires numpy >= 1.20, scipy >= 1.7, matplotlib >= 3.4.
The wall shooting solution is cached so energy and spectral diagnostics reuse it; a 50-point sign scan robustly brackets the nontrivial branch in the parameter range used here.
"""

import argparse
import os
from functools import lru_cache

import numpy as np
from scipy.integrate import solve_ivp
from scipy.linalg import eigh_tridiagonal
from scipy.optimize import brentq

_trapz = np.trapezoid if hasattr(np, "trapezoid") else np.trapz

VEV = 1.0
FIG_DIR = "figs/flrw"

dV = lambda p, lam: lam * p * (p ** 2 - VEV ** 2)
d2V = lambda p, lam: lam * (3.0 * p ** 2 - VEV ** 2)
CTN = {1: lambda x: 1.0 / np.tan(x), 0: lambda x: 1.0 / x, -1: lambda x: 1.0 / np.tanh(x)}


# ----------------------------------------------------------------------
# shooting from a regular center
# ----------------------------------------------------------------------
def shoot(phi0, lam, k, chi_end, eps=1e-8):
    """Integrate phi'' + 2 ctn_k phi' = V'(phi) outward from a regular center.

    Regularity forces phi'(0) = 0, so the local series is
    phi = phi0 + V'(phi0) chi^2/6 + O(chi^4); this fixes the initial data and
    is what makes the shooting problem one-dimensional.
    """
    c2 = dV(phi0, lam) / 6.0
    rhs = lambda x, y: [y[1], dV(y[0], lam) - 2.0 * CTN[k](x) * y[1]]
    return solve_ivp(rhs, (eps, chi_end), [phi0 + c2 * eps ** 2, 2.0 * c2 * eps],
                     rtol=1e-12, atol=1e-14, dense_output=True)


def nogo_scan(k, lam, chi_end=30.0, n=9):
    """Shoot from every admissible center value and record the endpoint."""
    return [(p0, shoot(p0, lam, k, chi_end).y[0, -1])
            for p0 in np.linspace(-VEV + 1e-9, -1e-3, n)]


# ----------------------------------------------------------------------
# the equatorial wall on S^3
# ----------------------------------------------------------------------
@lru_cache(maxsize=None)
def wall(lam, n_scan=50):
    """Antisymmetric wall: phi'(0) = 0 and phi(pi/2) = 0.

    The extension phi(pi - chi) = -phi(chi) then solves the equation on the
    whole of (0, pi) and is regular at both poles, because the equation is
    equivariant under chi -> pi - chi, phi -> -phi.
    """
    grid = np.linspace(-VEV + 1e-12, -1e-8, n_scan)
    end = np.array([shoot(p, lam, 1, np.pi / 2).y[0, -1] for p in grid])
    cross = np.flatnonzero(np.sign(end[:-1]) != np.sign(end[1:]))
    if cross.size == 0:
        return None
    i = cross[0]
    phi0 = brentq(lambda p: shoot(p, lam, 1, np.pi / 2).y[0, -1],
                  grid[i], grid[i + 1], xtol=1e-14)
    return phi0, shoot(phi0, lam, 1, np.pi / 2)


def wall_profile(lam, chi):
    """Full profile on (0, pi) by antisymmetric extension."""
    phi0, sol = wall(lam)
    mirror = np.minimum(chi, np.pi - chi)
    y, dy = sol.sol(mirror)
    sign = np.where(chi <= np.pi / 2, 1.0, -1.0)
    return phi0, sign * y, dy


def wall_energy(lam):
    phi0, sol = wall(lam)
    x = np.linspace(1e-8, np.pi / 2, 40000)
    p, dp = sol.sol(x)
    half = _trapz(np.sin(x) ** 2 * (0.5 * dp ** 2
                        + 0.25 * lam * (p ** 2 - VEV ** 2) ** 2), x)
    return 2.0 * 4.0 * np.pi * half


def wall_spectrum(lam, j, N=20000, cut=1e-4, n_levels=4):
    """Reduced Hessian -d^2/dchi^2 + V''(phi_0) - k/a^2 + j(j+1)/S_k^2, k = +1."""
    chi = np.linspace(cut, np.pi - cut, N)
    h = chi[1] - chi[0]
    _, y, _ = wall_profile(lam, chi)
    W = d2V(y, lam) - 1.0 + j * (j + 1) / np.sin(chi) ** 2
    return eigh_tridiagonal(2.0 / h ** 2 + W[1:-1], -np.ones(N - 3) / h ** 2,
                            eigvals_only=True, select='i',
                            select_range=(0, n_levels - 1))


# ----------------------------------------------------------------------
def table_nogo():
    print("\n(i) No centered radial interpolating solution on the noncompact sections.")
    print("    Endpoint phi(30) reached by shooting from a regular center:")
    for k, name in ((0, "R^3"), (-1, "H^3")):
        for lam in (1.0, 4.0, 10.0):
            vals = [e for _, e in nogo_scan(k, lam)]
            print("      %s  lambda=%4.1f : |phi(30)| <= %.3f  (never approaches +v)"
                   % (name, lam, np.max(np.abs(vals))))
    print("    Consistent with the virial identity: for k = 0, -1 both")
    print("    V(phi(0)) and int 2 ctn_k (phi')^2 are nonnegative and must sum")
    print("    to zero, which forces phi' = 0.")
    print("    Scope: centered, spherically symmetric profiles approaching one")
    print("    vacuum at infinity.  The planar kink is regular on R^3 and lies")
    print("    outside this class.")


def table_existence():
    print("\n(ii) Equatorial wall on S^3: existence threshold lambda v^2 a^2 = 3.")
    print("     lambda   wall?     phi(0)")
    for lam in (2.0, 2.9, 2.99, 3.01, 3.2, 4.0, 6.0, 10.0):
        r = wall(lam)
        print("     %6.2f   %-8s %s" % (lam, "no" if r is None else "yes",
                                        "" if r is None else "%.6f" % r[0]))
    print("     (the barrier-top solution phi = 0 has reduced spectrum")
    print("      n^2 - lambda v^2 a^2 - 1; the antisymmetric n = 2 level")
    print("      crosses zero at lambda v^2 a^2 = 3, where the wall bifurcates)")


def table_index():
    print("\n(iii) The wall is a sphaleron: Morse index 1, threefold kernel.")
    print("  (eigenvalues in units of a^{-2}; lambda varies, so not in units of lambda v^2)")
    print("  lambda   E/(4 pi sigma)   j=0 levels                    j=1 lowest    j=2 lowest")
    for lam in (3.2, 4.0, 6.0, 10.0):
        sigma = 2.0 * np.sqrt(2.0) / 3.0 * np.sqrt(lam) * VEV ** 3
        e = wall_energy(lam) / (4.0 * np.pi * sigma)
        s0 = wall_spectrum(lam, 0, n_levels=3)
        s1 = wall_spectrum(lam, 1, n_levels=2)
        s2 = wall_spectrum(lam, 2, n_levels=1)
        print("  %6.2f   %12.4f   %-28s  %-12.2e  %.3f"
               % (lam, e, np.array2string(np.round(s0, 4)), s1[0], s2[0]))
    print("  E/(4 pi sigma) -> 1: the thin-wall energy is the tension times the")
    print("  area 4 pi a^2 of a great two-sphere.  Exactly one negative s-wave")
    print("  level; the j = 1 zero is the isometry mode, exact to the quoted")
    print("  precision; j >= 2 strictly positive.")


def figure(outdir=FIG_DIR):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    os.makedirs(outdir, exist_ok=True)
    plt.rcParams.update({"font.family": "serif", "mathtext.fontset": "cm",
                         "font.size": 11, "axes.labelsize": 12, "legend.fontsize": 9,
                         "pdf.fonttype": 42, "ps.fonttype": 42,
                         "figure.dpi": 300, "savefig.bbox": "tight"})
    fig, ax = plt.subplots(1, 2, figsize=(11, 4.0))
    cols = ["#D55E00", "#009E73", "#0072B2", "#CC79A7"]
    dash = ["-", "--", "-.", (0, (3, 1, 1, 1))]
    chi = np.linspace(1e-4, np.pi - 1e-4, 4000)
    for c, ls, lam in zip(cols, dash, (3.2, 4.0, 6.0, 10.0)):
        _, y, _ = wall_profile(lam, chi)
        ax[0].plot(chi, y, linestyle=ls, color=c, lw=1.8,
                   label=r"$\lambda v^2a^2=%.1f$" % lam)
    ax[0].axhline(1, color="0.7", lw=0.7, ls=":")
    ax[0].axhline(-1, color="0.7", lw=0.7, ls=":")
    ax[0].axvline(np.pi / 2, color="0.7", lw=0.7, ls=":")
    ax[0].set_xlabel(r"$\chi$")
    ax[0].set_ylabel(r"$\phi_0(\chi)/v$")
    ax[0].set_xlim(0, np.pi)
    ax[0].set_title("(a) equatorial walls on $S^3$", fontsize=11)
    ax[0].legend(frameon=False, loc="upper left")

    lams = np.linspace(3.02, 12.0, 18)
    amp = [-wall(l)[0] for l in lams]
    ax[1].plot(lams, amp, "-", color="#0072B2", lw=1.8, label=r"$-\phi_0(0)/v$")
    ener = [wall_energy(l) / (4 * np.pi * 2 * np.sqrt(2) / 3 * np.sqrt(l)) for l in lams]
    ax[1].plot(lams, ener, "--", color="#D55E00", lw=1.8,
               label=r"$E/(4\pi a^2\sigma)$")
    ax[1].axvline(3.0, color="0.5", lw=0.9, ls=":")
    ax[1].text(3.15, 0.35, r"bifurcation at $\lambda v^2a^2=3$", fontsize=9, rotation=90)
    ax[1].axhline(1.0, color="0.7", lw=0.7, ls=":")
    ax[1].set_xlabel(r"$\lambda v^2a^2$")
    ax[1].set_ylim(0, 1.15)
    ax[1].set_title("(b) amplitude and thin-wall energy", fontsize=11)
    ax[1].legend(frameon=False, loc="lower right")
    fig.tight_layout(w_pad=2.5)
    fig.savefig(os.path.join(outdir, "fig4_wall.pdf"))
    plt.close(fig)
    print("\nfigure written to %s/fig4_wall.pdf" % outdir)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--figure", action="store_true")
    args, _ = ap.parse_known_args()
    table_nogo()
    table_existence()
    table_index()
    if args.figure:
        figure()


if __name__ == "__main__":
    main()